### ISSUE TITLE
Add 'paper.md' for JOSS

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/mcbette#15]
See [my rOpenSci submission](https://github.com/ropensci/software-review/issues/360) in which I state I'd enjoy a JOSS article.

**Comment by maelle** [comment]
Is there any ETA on this?

**Comment by richelbilderbeek** [comment]
@maelle: no, not yet. Would March 2nd be good enough?

**Comment by maelle** [comment]
I think so, I'd like the reviewers to be able to read it

**Comment by richelbilderbeek** [comment]
OK, I can guarantee a well-written draft this Saturday, but I cannot guarantee a polished article. Will that work for starters? Else, maybe I should postpone my review request?

**Comment by maelle** [comment]
I suppose it's better to put the submission on hold indeed if @vbaliga is still available a bit later.

**Comment by richelbilderbeek** [comment]
If you think so, I will follow your lead :+1:

I am sorry, the JOSS article is both new to me and seems great!

**Comment by maelle** [comment]
no problem (it's a very short article :-) ).

**Comment by vbaliga** [comment]
No worries on my end - I can be flexible on timing

**Comment by richelbilderbeek** [comment]
Thanks @vbaliga!

**Comment by richelbilderbeek** [comment]
@maelle: I've added the JOSS paper, at [the place where one would expect it](https://github.com/richelbilderbeek/mcbette/blob/master/paper.md).

Closing this Issue :+1:
