### ISSUE TITLE
Use https in links to BEAST2 in all packages

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/mcbette#18]
From [here](https://github.com/ropensci/software-review/issues/360), thanks @maelle:

> The link to BEAST2 in DESCRIPTION uses http, please replace it with https <https://www.beast2.org/> (I made a PR). If you used the http link in other packages, you can change it but that is obviously beyond the scope of my checks. wink

Do this in all packages.

**Comment by maelle** [comment]
http->https was part of the work we did on rOpenSci website btw https://ropensci.org/technotes/2019/12/19/urls-tidying/

**Comment by richelbilderbeek** [comment]
Done :+1:
