### ISSUE TITLE
Installation on cluster, issue with Rmpfr

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/mcbette#5]
One of the dependencies of mcbette; Rmpfr; doesn't install for me on the cluster, I receive the following error:

> 
> > install.packages("Rmpfr")
> Installing package into ‘/home/p251362/R/x86_64-pc-linux-gnu-library/3.5’
> (as ‘lib’ is unspecified)
> trying URL 'https://ftp.fau.de/cran/src/contrib/Rmpfr_0.7-2.tar.gz'
> Content type 'application/x-gzip' length 626031 bytes (611 KB)
> ==================================================
> downloaded 611 KB
> 
> * installing *source* package ‘Rmpfr’ ...
> ** package ‘Rmpfr’ successfully unpacked and MD5 sums checked
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking mpfr.h usability... no
> checking mpfr.h presence... no
> checking for mpfr.h... no
> configure: error: Header file mpfr.h not found; maybe use --with-mpfr-include=INCLUDE_PATH
> ERROR: configuration failed for package ‘Rmpfr’
> * removing ‘/home/p251362/R/x86_64-pc-linux-gnu-library/3.5/Rmpfr’

Apparently, this is a known issue: https://stackoverflow.com/questions/33750315/installation-of-package-rmpfr-had-non-zero-exit-status and https://stackoverflow.com/questions/28868789/error-when-trying-to-install-rmpfr-in-r-related-to-the-header-file-mpfr-h

Commonly fixed by installing the mpfr libraries, for which you need sudo, which I don't have on the cluster.

Is there any way to make mcbette run without Rmpfr ?

**Comment by richelbilderbeek** [comment]
Thanks for this Issue! Of course, this is not strictly a `mcbette` Issue at all, but it's good to have this solution somewhere.

On the Peregrine cluster, one needs to load modules. I have not tested it, but I guess this would work:

```
module spider MPFR
```

Run this before running `mcbette`. 

How can I know? Because I did this:

```
p230198@peregrine:~ module spider mpfr

----------------------------------------------------------------------------
  MPFR:
----------------------------------------------------------------------------
    Description:
      The MPFR library is a C library for multiple-precision floating-point
      computations with correct rounding. 

     Versions:
        MPFR/3.1.4-foss-2016a
        MPFR/4.0.1-GCCcore-6.4.0

----------------------------------------------------------------------------
  For detailed information about a specific "MPFR" module (including how to load
 the modules) use the module's full name.
  For example:

     $ module spider MPFR/4.0.1-GCCcore-6.4.0
----------------------------------------------------------------------------
```

Would be helpful if you would confirm this works yes/no :+1:

**Comment by thijsjanzen** [comment]
Yes this works.

In a moment of brainfreeze I had spidered for this module:

`module spider Rmpfr`

And not found anything... but off course that is the package, and not the external library :)

Using module load MPFR/4.0.1-GCCcore-6.4.0 starting the R session fixed the issue.

**Comment by richelbilderbeek** [comment]
Thanks for verifying the solution :+1:
