### ISSUE TITLE
Only NA results

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/mcbette#6]
This might very well be a product of my alignment, but I find it very hard to debug/find the issue.

I have ran mcbette on the cluster (on Travis the run times out after 47 minutes (!)). 
I run the following code:
```
library(mcbette)
f <- list.files(pattern = "*.fasta")
for(x in f) {
	df <- mcbette::est_marg_liks(
		  fasta_filename = x, verbose = TRUE
	)
	saveRDS(df, file = "results.RData")
	write.table(df, file = "results.txt")
}
```
With the following alignment:
[RH1_trimal2.fasta.zip](https://github.com/richelbilderbeek/mcbette/files/2956215/RH1_trimal2.fasta.zip)

This results in the following error messages:

> <simpleError: all(file.exists(output_log_filename)) is not TRUE>
> <simpleError: all(file.exists(output_log_filename)) is not TRUE>
>  ...
> <simpleError: all(file.exists(output_log_filename)) is not TRUE>
> There were 50 or more warnings (use warnings() to see the first 50)

and the results.txt file can be found here:
[results.txt](https://github.com/richelbilderbeek/mcbette/files/2956228/results.txt)

Clearly, something is going wrong, causing NA values for all models. However, I don't know what - it could be some sample naming issues in the fasta file, or perhaps something else. I would love to run a single model with detailed output in mcbette, to see where the error arises.

**Comment by richelbilderbeek** [comment]
This is similar to Issue ['file.exists(output_log_filename) is not TRUE'](https://github.com/ropensci/babette/issues/65).

Peregrine (or MacOS in the earlier case) has a problem with `tempfile`. Workaround is to specify the paths of all (usually temporary) files.

I cannot try at the moment, but here the gist of it:

```r
est_marg_liks_from_models(
  fasta_filename,
  beast2_optionses = list(
    beastier::create_beast2_options(
      # Filenames here
    )
  )
)
``` 

I predict that will help :+1:

**Comment by thijsjanzen** [comment]
Yeah... that sounds reasonable, but kind of doesn't work some how:
```r
df <- mcbette::est_marg_liks_from_models(
		fasta_filename = "RH1_trimal2.fasta",
		beast2_optionses = list(
    			beastier::create_beast2_options(
      				output_log_filename = "my.log",
				output_trees_filename = "my.trees",
				output_state_filename = "my.state",
				overwrite = TRUE,
				verbose = TRUE
			)

		),    			   
		verbose = TRUE
	)
```
yields:
```
Error in mcbette::est_marg_liks_from_models(fasta_filename = "RH1_trimal2.fasta",  : 
  'inference_models' must have 'mcmc's for nested sampling.
Tip: use 'beautier::create_nested_sampling_mcmc'
Execution halted
```

which suggests that the default argument in `est_marg_liks_from_models` for 'inference_models' does not yield executable code. The default argument is: `inference_models = list(beautier::create_inference_model())`.

**Comment by richelbilderbeek** [comment]
Thanks for pointing out a lack of documentation there!

I've added [some example code to the function](https://github.com/richelbilderbeek/mcbette/blob/develop/R/est_marg_liks_from_models.R), thanking you in the commit,

Here is how to create an inference model that does employ the requested nested sampling:

```r
inference_model_1 <- beautier::create_inference_model(
  mcmc = beautier::create_nested_sampling_mcmc()
)
```

**Comment by thijsjanzen** [comment]
Ahaaaa! Now we are getting closer to the actual true issue underlying the NA entries:

Upon running:
```r
df <- mcbette::est_marg_liks_from_models(
		 fasta_filename = "RH1_trimal2.fasta",
		 inference_models = list(  
                                 beautier::create_inference_model(
                                            mcmc = beautier::create_nested_sampling_mcmc()
                                  )
                  ),
		 beast2_optionses = list(
    			beastier::create_beast2_options(
      				output_log_filename = "my.log",
				output_trees_filename = "my.trees",
				output_state_filename = "my.state",
				overwrite = TRUE,
				verbose = TRUE
			)
		),    			   
		verbose = TRUE
	)
```

I receive:
```
[1] "Estimating evidence for model 1/1 with JC69 site model, strict clock model and yule tree prior"
<simpleError in bbt_check_beast2_packages(mcmc = mcmc, beast2_path = beast2_path): When using nested sampling (that is, using 'create_mcmc_nested_sampling'), one must use the binary BEAST2 executable (that is, using 'beast2_path = get_default_beast2_bin_path()')>
[1] "Log evidence for model 1/1: NA"
```

**Comment by richelbilderbeek** [comment]
Yup, your suggestion is good. Added this and thanked you in the commit message. Next to that:

Thanks :+1: 

Problem solved?

**Comment by thijsjanzen** [comment]
> Yup, your suggestion is good. Added this and thanked you in the commit message. Next to that:
> 
> Thanks 👍
> 
> Problem solved?

Well... now I need to see how to test all 40 models :)

**Comment by richelbilderbeek** [comment]
Perhaps `pirouette` can help out here, as it can compare and run all 40 models.

**Comment by thijsjanzen** [comment]
> Perhaps `pirouette` can help out here, as it can compare and run all 40 models?
> 
> I'd enjoy you try that one out as well 👍

Wait... but mcbette::est_marg_liks does that too!
It just doesn't take beast2 options as argument for some reason :)

**Comment by richelbilderbeek** [comment]
Let's clarify: `mcbette` finds the best inference model, based on an alignment. `mcbette` does not run that actual best inference model to create a Bayesian posterior.

`pirouette` can find a best inference model and run all inference models (regardless of their weights) to produce 40 Bayesian posteriors.

Interested?

**Comment by thijsjanzen** [comment]
> Let's clarify: `mcbette` finds the best inference model, based on an alignment. `mcbette` does not run that actual best inference model to create a Bayesian posterior.
> 
> `pirouette` can find a best inference model and run all inference models (regardless of their weights) to produce 40 Bayesian posteriors.
> 
> Interested?

Right now I'm just trying to find the best inference model, based on my alignment. I aim to do this for 6 genes separately, and then use these best fitting models in a STARBEAST2 analysis.

**Comment by richelbilderbeek** [comment]
Ah, `pirouette` cannot do that. Good luck :+1:
